config/routes.rb
Rails.application.routes.draw do

  resources :items
  root 'items#index'
  
  get 'thanks_page', to: 'thanks_page#view'
  post 'thanks_page', to: 'thanks_page#view'  
  get    'admin'   => 'sessions#new'
  post   'admin'   => 'sessions#create'
  
  get 'list', to: 'sessions#list'
  post   'list', to: 'sessions#list'
end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def index
    @items = Item.all
  end

  def show
  end
  
  
  def new
    @item = Item.new
  end

  def edit
  end

  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_item
      @item = Item.find(params[:id])
    end

    def item_params
      params.require(:item).permit(:itemName, :price, :stock)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def list
    @items = Item.all
  end
 
 
end

app/controllers/thanks_page_controller.rb
class ThanksPageController < ApplicationController
  def view
    @items = Item.all
  end
  
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper

 # ページごとの完全なタイトルを返す
  def full_title(page_title = '')
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
  
  def item_image_tag item
    case item.id
    when 1
      image_tag 'daikon.jpeg'
    when 2
      image_tag 'shintama.jpeg'
    when 3
      image_tag 'ninjin.jpeg'
    when 4
      image_tag 'imo.jpeg'
    when 5
      image_tag 'buta3.jpeg'
    end
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/thanks_page_helper.rb
module ThanksPageHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :itemName %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :stock %><br>
    <%= f.number_field :stock %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>商品編集</h1>

<%= render 'form' %>

<%= link_to 'Back', list_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>"SHOP_APPへようこそ"</h1>

<%= form_tag "thanks_page", method: "POST" do %>
  <table class="items table" style="border:5px;">
    <thead>
      <tr>
        <th></th>
        <th>商品名</th>
        <th>単価</th>
        <th>個数</th>
        <th class="kingaku">金額</th>
      </tr>
    </thead>

    <tbody>
      <% @items.each do |item| %>
        <tr class="item">
          <td><%= item_image_tag item %></td>
          <td style="font-size: 24px;"><%= item.name %></td>
          <td style="font-size: 24px;"><span class="unit"><%= item.price %>円</span></td>
          <td style="font-size: 24px;">
            <%= select_tag "item",options_for_select((0..(item.stock)).to_a, 0), class: "quantity" %>
          </td>
          <td style="font-size: 24px;">
            <%= number_field "money", 0,{placeholder: 1, class: "amount", readonly: true}  %>
          </td>
        </tr>
      <% end %>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td class="total" style="font-size: 24px;"><%= number_field "value", 0,{placeholder: 1, class: "totalAmount",readonly: true}  %></td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td>

          <td></td>
          <td><%= submit_tag "buy", data: { confirm: "購入してよいですか？", disable_with: "送信中..." },id:"submit",class:"btn btn-success"   %></td>

        </tr>
    </tbody>
  </table>
<% end %>

app/views/items/index2.html.erb
<p id="notice"><%= notice %></p>

<h1>"SHOP_APPへようこそ"</h1>

<%= form_tag "thanks_page", method: "GET" do %>
  <table class="items table" style="border:5px;">
    <thead>
      <tr>
        <th></th>
        <th>商品名</th>
        <th>単価</th>
        <th>個数</th>
        <th class="kingaku">金額</th>
      </tr>
    </thead>

    <tbody>
      <% @items.each do |item| %>
        <tr class="item">
          <td><%= item_image_tag item %></td>
          <td style="font-size: 24px;"><%= item.name %></td>
          <td style="font-size: 24px;"><span class="unit"><%= item.price %>円</span></td>
          <td style="font-size: 24px;">
            <%= select_tag "item_#{item.id}",options_for_select((0..(item.stock)).to_a, 0), class: "quantity" %>
          </td>
          <td style="font-size: 24px;">
            <%= number_field "money#{item.id}", 0,{placeholder: 1, class: "amount",:disabled => true}  %>
          </td>
        </tr>
      <% end %>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td class="total" style="font-size: 24px;"><%= number_field "value", 0,{placeholder: 1, class: "totalAmount",:disabled => true}  %></td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td>

          <td></td>

          <td><%= submit_tag "購入", data: { confirm: "購入してよいですか？", disable_with: "送信中..." },id:"submit",class:"btn btn-success"   %></td>

        </tr>
    </tbody>
  </table>
<% end %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

<%= link_to 'Back', list_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Itemname:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @item.stock %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Team Hawks</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "shop app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",  root_path %></li>
        <li><%= link_to "Admin", 'admin' %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                        'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/thanks_page/view.html.erb
<p>ご購入ありがとうございます！！</p>
<table id="cart" class="table ">
  <thead>
    <tr>
      <th style="font-size: 24px;">商品名</th>
      <th style="font-size: 24px;">個数</th>
      <th style="font-size: 24px;">金額</th>
    </tr>
  </thead>
  <tbody>
      <tr>
        <td style="font-size: 20px;"></td>
        <td style="font-size: 20px;"></td>
        <td style="font-size: 20px;"></td>
      </tr>
      <tr>
        <td colspan="2"></td>
        <td style="font-size: 20px;">合計<%= params[:value]["0"] %>円です</td>
      </tr>

  </tbody>
</table>